language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - hhvm

before_script:
  - wget http://getcomposer.org/composer.phar
  - php composer.phar self-update
  - php composer.phar install --no-interaction

script:
  - mkdir -p build/logs
  - phpunit tests

matrix:
  fast_finish: true
  allow_failures:
      - php: hhvm
